CREATE UNIQUE INDEX calendar_events_pkey ON public.calendar_events USING btree (id);
CREATE INDEX idx_calendar_events_ws ON public.calendar_events USING btree (workspace_id);
CREATE INDEX idx_calendar_user_date ON public.calendar_events USING btree (user_id, event_date);
CREATE UNIQUE INDEX checklist_daily_completions_pkey ON public.checklist_daily_completions USING btree (id);
CREATE UNIQUE INDEX checklist_daily_completions_workspace_id_task_id_completed__key ON public.checklist_daily_completions USING btree (workspace_id, task_id, completed_on);
CREATE INDEX idx_checklist_daily_completions_ws_date ON public.checklist_daily_completions USING btree (workspace_id, completed_on DESC);
CREATE UNIQUE INDEX checklist_tasks_pkey ON public.checklist_tasks USING btree (id);
CREATE INDEX idx_checklist_tasks_column ON public.checklist_tasks USING btree (column_id);
CREATE INDEX idx_checklist_tasks_owner_company ON public.checklist_tasks USING btree (owner_email, company, "position");
CREATE INDEX idx_checklist_tasks_parent ON public.checklist_tasks USING btree (parent_id);
CREATE INDEX idx_checklist_tasks_parent_id ON public.checklist_tasks USING btree (parent_id);
CREATE INDEX idx_checklist_tasks_user ON public.checklist_tasks USING btree (user_id);
CREATE INDEX idx_checklist_tasks_workspace_parent ON public.checklist_tasks USING btree (workspace_id, parent_id);
CREATE INDEX idx_checklist_tasks_ws ON public.checklist_tasks USING btree (workspace_id);
CREATE INDEX idx_checklist_tasks_ws_funnel ON public.checklist_tasks USING btree (workspace_id, funnel_id);
CREATE UNIQUE INDEX crm_leads_pkey ON public.crm_leads USING btree (id);
CREATE INDEX idx_crm_leads_ws ON public.crm_leads USING btree (workspace_id);
CREATE INDEX idx_crm_user ON public.crm_leads USING btree (user_id);
CREATE UNIQUE INDEX finance_categories_pkey ON public.finance_categories USING btree (id);
CREATE INDEX idx_fin_cat_ws ON public.finance_categories USING btree (workspace_id);
CREATE UNIQUE INDEX finance_costs_pkey ON public.finance_costs USING btree (id);
CREATE INDEX idx_fin_costs_ws ON public.finance_costs USING btree (workspace_id);
CREATE UNIQUE INDEX finance_products_pkey ON public.finance_products USING btree (id);
CREATE INDEX idx_fin_products_ws ON public.finance_products USING btree (workspace_id);
CREATE UNIQUE INDEX finance_transactions_pkey ON public.finance_transactions USING btree (id);
CREATE INDEX idx_fin_tx_ws_date ON public.finance_transactions USING btree (workspace_id, occurred_on DESC);
CREATE UNIQUE INDEX gratitude_entries_pkey ON public.gratitude_entries USING btree (id);
CREATE UNIQUE INDEX gratitude_entries_user_id_entry_date_key ON public.gratitude_entries USING btree (user_id, entry_date);
CREATE INDEX idx_gratitude_entries_user_date ON public.gratitude_entries USING btree (user_id, entry_date DESC);
CREATE INDEX idx_kanban_attachments_card ON public.kanban_attachments USING btree (card_id);
CREATE UNIQUE INDEX kanban_attachments_pkey ON public.kanban_attachments USING btree (id);
CREATE INDEX idx_kanban_cards_column ON public.kanban_cards USING btree (column_id);
CREATE INDEX idx_kanban_cards_ws_funnel ON public.kanban_cards USING btree (workspace_id, funnel_id);
CREATE UNIQUE INDEX kanban_cards_pkey1 ON public.kanban_cards USING btree (id);
CREATE INDEX idx_kanban_cards_funnel ON public.kanban_cards_archive USING btree (funnel_id);
CREATE INDEX idx_kanban_cards_ws ON public.kanban_cards_archive USING btree (workspace_id);
CREATE INDEX idx_kanban_user ON public.kanban_cards_archive USING btree (user_id);
CREATE INDEX kanban_cards_column_id_idx ON public.kanban_cards_archive USING btree (column_id);
CREATE UNIQUE INDEX kanban_cards_pkey ON public.kanban_cards_archive USING btree (id);
CREATE INDEX idx_kanban_columns_funnel ON public.kanban_columns USING btree (funnel_id);
CREATE INDEX idx_kanban_columns_ws ON public.kanban_columns USING btree (workspace_id);
CREATE UNIQUE INDEX kanban_columns_pkey ON public.kanban_columns USING btree (id);
CREATE INDEX kanban_columns_user_position_idx ON public.kanban_columns USING btree (user_id, "position");
CREATE UNIQUE INDEX kanban_funnels_pkey ON public.kanban_funnels USING btree (id);
CREATE INDEX idx_note_categories_ws ON public.note_categories USING btree (workspace_id);
CREATE UNIQUE INDEX note_categories_pkey ON public.note_categories USING btree (id);
CREATE UNIQUE INDEX note_categories_user_id_name_key ON public.note_categories USING btree (user_id, name);
CREATE INDEX idx_notes_ws ON public.notes USING btree (workspace_id);
CREATE UNIQUE INDEX notes_pkey ON public.notes USING btree (id);
CREATE INDEX notes_user_category_idx ON public.notes USING btree (user_id, category);
CREATE INDEX notes_user_updated_idx ON public.notes USING btree (user_id, updated_at DESC);
CREATE INDEX idx_ponto_session_edits_session ON public.ponto_session_edits USING btree (session_id);
CREATE INDEX idx_ponto_session_edits_workspace ON public.ponto_session_edits USING btree (workspace_id, created_at DESC);
CREATE UNIQUE INDEX ponto_session_edits_pkey ON public.ponto_session_edits USING btree (id);
CREATE INDEX idx_ponto_session_tasks_owner ON public.ponto_session_tasks USING btree (owner_email, completed_at DESC);
CREATE INDEX idx_ponto_session_tasks_session ON public.ponto_session_tasks USING btree (session_id);
CREATE INDEX idx_ponto_session_tasks_user ON public.ponto_session_tasks USING btree (user_id);
CREATE INDEX idx_ponto_session_tasks_ws ON public.ponto_session_tasks USING btree (workspace_id);
CREATE UNIQUE INDEX ponto_session_tasks_pkey ON public.ponto_session_tasks USING btree (id);
CREATE UNIQUE INDEX idx_ponto_one_active_per_user_workspace ON public.ponto_sessions USING btree (workspace_id, user_id) WHERE ((status = ANY (ARRAY['working'::text, 'paused'::text])) AND (user_id IS NOT NULL));
CREATE INDEX idx_ponto_sessions_history_lookup ON public.ponto_sessions USING btree (workspace_id, user_id, started_at DESC);
CREATE INDEX idx_ponto_sessions_open_activity ON public.ponto_sessions USING btree (updated_at) WHERE (status = ANY (ARRAY['working'::text, 'paused'::text]));
CREATE INDEX idx_ponto_sessions_owner ON public.ponto_sessions USING btree (owner_email, started_at DESC);
CREATE INDEX idx_ponto_sessions_user ON public.ponto_sessions USING btree (user_id);
CREATE INDEX idx_ponto_sessions_ws ON public.ponto_sessions USING btree (workspace_id);
CREATE INDEX idx_ponto_sessions_ws_user_company_started ON public.ponto_sessions USING btree (workspace_id, user_id, company, started_at DESC);
CREATE INDEX idx_ponto_sessions_ws_user_started ON public.ponto_sessions USING btree (workspace_id, user_id, started_at DESC);
CREATE UNIQUE INDEX ponto_sessions_pkey ON public.ponto_sessions USING btree (id);
CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);
CREATE INDEX idx_sticky_notes_ws ON public.sticky_notes USING btree (workspace_id, "position");
CREATE UNIQUE INDEX sticky_notes_pkey ON public.sticky_notes USING btree (id);
CREATE INDEX idx_stock_categories_company ON public.stock_categories USING btree (workspace_id, company_id);
CREATE UNIQUE INDEX stock_categories_pkey ON public.stock_categories USING btree (id);
CREATE UNIQUE INDEX stock_companies_pkey ON public.stock_companies USING btree (id);
CREATE UNIQUE INDEX stock_companies_workspace_id_slug_key ON public.stock_companies USING btree (workspace_id, slug);
CREATE INDEX idx_stock_field_defs_company ON public.stock_field_defs USING btree (workspace_id, company_id);
CREATE UNIQUE INDEX stock_field_defs_company_id_key_key ON public.stock_field_defs USING btree (company_id, key);
CREATE UNIQUE INDEX stock_field_defs_pkey ON public.stock_field_defs USING btree (id);
CREATE INDEX idx_stock_groups_company ON public.stock_groups USING btree (workspace_id, company_id);
CREATE UNIQUE INDEX stock_groups_pkey ON public.stock_groups USING btree (id);
CREATE INDEX idx_stock_items_company ON public.stock_items USING btree (workspace_id, company_id);
CREATE INDEX idx_stock_items_ws ON public.stock_items USING btree (workspace_id);
CREATE UNIQUE INDEX stock_items_pkey ON public.stock_items USING btree (id);
CREATE INDEX idx_stock_movements_company ON public.stock_movements USING btree (workspace_id, company_id);
CREATE INDEX idx_stock_movements_item ON public.stock_movements USING btree (item_id);
CREATE INDEX idx_stock_movements_ws ON public.stock_movements USING btree (workspace_id);
CREATE UNIQUE INDEX stock_movements_pkey ON public.stock_movements USING btree (id);
CREATE UNIQUE INDEX user_roles_pkey ON public.user_roles USING btree (id);
CREATE UNIQUE INDEX user_roles_user_id_role_key ON public.user_roles USING btree (user_id, role);
CREATE UNIQUE INDEX workspace_members_pkey ON public.workspace_members USING btree (id);
CREATE UNIQUE INDEX workspace_members_workspace_id_user_id_key ON public.workspace_members USING btree (workspace_id, user_id);
CREATE UNIQUE INDEX workspaces_pkey ON public.workspaces USING btree (id);
CREATE UNIQUE INDEX workspaces_slug_key ON public.workspaces USING btree (slug);
