/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTrendsRouteImport } from './routes/app.trends'
import { Route as AppStockRouteImport } from './routes/app.stock'
import { Route as AppStickyNotesRouteImport } from './routes/app.sticky-notes'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppNotesRouteImport } from './routes/app.notes'
import { Route as AppKanbanRouteImport } from './routes/app.kanban'
import { Route as AppGratitudeRouteImport } from './routes/app.gratitude'
import { Route as AppFinanceRouteImport } from './routes/app.finance'
import { Route as AppFilesRouteImport } from './routes/app.files'
import { Route as AppDiscographyRouteImport } from './routes/app.discography'
import { Route as AppCrmRouteImport } from './routes/app.crm'
import { Route as AppCompaniesRouteImport } from './routes/app.companies'
import { Route as AppCityRouteImport } from './routes/app.city'
import { Route as AppChecklistsRouteImport } from './routes/app.checklists'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppCalculatorRouteImport } from './routes/app.calculator'
import { Route as AppCalc3dRouteImport } from './routes/app.calc3d'
import { Route as AppAdminAccountsRouteImport } from './routes/app.admin-accounts'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTrendsRoute = AppTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => AppRoute,
} as any)
const AppStockRoute = AppStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AppRoute,
} as any)
const AppStickyNotesRoute = AppStickyNotesRouteImport.update({
  id: '/sticky-notes',
  path: '/sticky-notes',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppKanbanRoute = AppKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AppRoute,
} as any)
const AppGratitudeRoute = AppGratitudeRouteImport.update({
  id: '/gratitude',
  path: '/gratitude',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppFilesRoute = AppFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscographyRoute = AppDiscographyRouteImport.update({
  id: '/discography',
  path: '/discography',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesRoute = AppCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AppRoute,
} as any)
const AppCityRoute = AppCityRouteImport.update({
  id: '/city',
  path: '/city',
  getParentRoute: () => AppRoute,
} as any)
const AppChecklistsRoute = AppChecklistsRouteImport.update({
  id: '/checklists',
  path: '/checklists',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppCalculatorRoute = AppCalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => AppRoute,
} as any)
const AppCalc3dRoute = AppCalc3dRouteImport.update({
  id: '/calc3d',
  path: '/calc3d',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAccountsRoute = AppAdminAccountsRouteImport.update({
  id: '/admin-accounts',
  path: '/admin-accounts',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/admin-accounts': typeof AppAdminAccountsRoute
  '/app/calc3d': typeof AppCalc3dRoute
  '/app/calculator': typeof AppCalculatorRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/checklists': typeof AppChecklistsRoute
  '/app/city': typeof AppCityRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/crm': typeof AppCrmRoute
  '/app/discography': typeof AppDiscographyRoute
  '/app/files': typeof AppFilesRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/gratitude': typeof AppGratitudeRoute
  '/app/kanban': typeof AppKanbanRoute
  '/app/notes': typeof AppNotesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/sticky-notes': typeof AppStickyNotesRoute
  '/app/stock': typeof AppStockRoute
  '/app/trends': typeof AppTrendsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/admin-accounts': typeof AppAdminAccountsRoute
  '/app/calc3d': typeof AppCalc3dRoute
  '/app/calculator': typeof AppCalculatorRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/checklists': typeof AppChecklistsRoute
  '/app/city': typeof AppCityRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/crm': typeof AppCrmRoute
  '/app/discography': typeof AppDiscographyRoute
  '/app/files': typeof AppFilesRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/gratitude': typeof AppGratitudeRoute
  '/app/kanban': typeof AppKanbanRoute
  '/app/notes': typeof AppNotesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/sticky-notes': typeof AppStickyNotesRoute
  '/app/stock': typeof AppStockRoute
  '/app/trends': typeof AppTrendsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/admin-accounts': typeof AppAdminAccountsRoute
  '/app/calc3d': typeof AppCalc3dRoute
  '/app/calculator': typeof AppCalculatorRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/checklists': typeof AppChecklistsRoute
  '/app/city': typeof AppCityRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/crm': typeof AppCrmRoute
  '/app/discography': typeof AppDiscographyRoute
  '/app/files': typeof AppFilesRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/gratitude': typeof AppGratitudeRoute
  '/app/kanban': typeof AppKanbanRoute
  '/app/notes': typeof AppNotesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/sticky-notes': typeof AppStickyNotesRoute
  '/app/stock': typeof AppStockRoute
  '/app/trends': typeof AppTrendsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/reset-password'
    | '/app/admin-accounts'
    | '/app/calc3d'
    | '/app/calculator'
    | '/app/calendar'
    | '/app/checklists'
    | '/app/city'
    | '/app/companies'
    | '/app/crm'
    | '/app/discography'
    | '/app/files'
    | '/app/finance'
    | '/app/gratitude'
    | '/app/kanban'
    | '/app/notes'
    | '/app/settings'
    | '/app/sticky-notes'
    | '/app/stock'
    | '/app/trends'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/app/admin-accounts'
    | '/app/calc3d'
    | '/app/calculator'
    | '/app/calendar'
    | '/app/checklists'
    | '/app/city'
    | '/app/companies'
    | '/app/crm'
    | '/app/discography'
    | '/app/files'
    | '/app/finance'
    | '/app/gratitude'
    | '/app/kanban'
    | '/app/notes'
    | '/app/settings'
    | '/app/sticky-notes'
    | '/app/stock'
    | '/app/trends'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/reset-password'
    | '/app/admin-accounts'
    | '/app/calc3d'
    | '/app/calculator'
    | '/app/calendar'
    | '/app/checklists'
    | '/app/city'
    | '/app/companies'
    | '/app/crm'
    | '/app/discography'
    | '/app/files'
    | '/app/finance'
    | '/app/gratitude'
    | '/app/kanban'
    | '/app/notes'
    | '/app/settings'
    | '/app/sticky-notes'
    | '/app/stock'
    | '/app/trends'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trends': {
      id: '/app/trends'
      path: '/trends'
      fullPath: '/app/trends'
      preLoaderRoute: typeof AppTrendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stock': {
      id: '/app/stock'
      path: '/stock'
      fullPath: '/app/stock'
      preLoaderRoute: typeof AppStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sticky-notes': {
      id: '/app/sticky-notes'
      path: '/sticky-notes'
      fullPath: '/app/sticky-notes'
      preLoaderRoute: typeof AppStickyNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notes': {
      id: '/app/notes'
      path: '/notes'
      fullPath: '/app/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kanban': {
      id: '/app/kanban'
      path: '/kanban'
      fullPath: '/app/kanban'
      preLoaderRoute: typeof AppKanbanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gratitude': {
      id: '/app/gratitude'
      path: '/gratitude'
      fullPath: '/app/gratitude'
      preLoaderRoute: typeof AppGratitudeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance': {
      id: '/app/finance'
      path: '/finance'
      fullPath: '/app/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/files': {
      id: '/app/files'
      path: '/files'
      fullPath: '/app/files'
      preLoaderRoute: typeof AppFilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/discography': {
      id: '/app/discography'
      path: '/discography'
      fullPath: '/app/discography'
      preLoaderRoute: typeof AppDiscographyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm': {
      id: '/app/crm'
      path: '/crm'
      fullPath: '/app/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/companies': {
      id: '/app/companies'
      path: '/companies'
      fullPath: '/app/companies'
      preLoaderRoute: typeof AppCompaniesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/city': {
      id: '/app/city'
      path: '/city'
      fullPath: '/app/city'
      preLoaderRoute: typeof AppCityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/checklists': {
      id: '/app/checklists'
      path: '/checklists'
      fullPath: '/app/checklists'
      preLoaderRoute: typeof AppChecklistsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calculator': {
      id: '/app/calculator'
      path: '/calculator'
      fullPath: '/app/calculator'
      preLoaderRoute: typeof AppCalculatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calc3d': {
      id: '/app/calc3d'
      path: '/calc3d'
      fullPath: '/app/calc3d'
      preLoaderRoute: typeof AppCalc3dRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin-accounts': {
      id: '/app/admin-accounts'
      path: '/admin-accounts'
      fullPath: '/app/admin-accounts'
      preLoaderRoute: typeof AppAdminAccountsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminAccountsRoute: typeof AppAdminAccountsRoute
  AppCalc3dRoute: typeof AppCalc3dRoute
  AppCalculatorRoute: typeof AppCalculatorRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppChecklistsRoute: typeof AppChecklistsRoute
  AppCityRoute: typeof AppCityRoute
  AppCompaniesRoute: typeof AppCompaniesRoute
  AppCrmRoute: typeof AppCrmRoute
  AppDiscographyRoute: typeof AppDiscographyRoute
  AppFilesRoute: typeof AppFilesRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppGratitudeRoute: typeof AppGratitudeRoute
  AppKanbanRoute: typeof AppKanbanRoute
  AppNotesRoute: typeof AppNotesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStickyNotesRoute: typeof AppStickyNotesRoute
  AppStockRoute: typeof AppStockRoute
  AppTrendsRoute: typeof AppTrendsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminAccountsRoute: AppAdminAccountsRoute,
  AppCalc3dRoute: AppCalc3dRoute,
  AppCalculatorRoute: AppCalculatorRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppChecklistsRoute: AppChecklistsRoute,
  AppCityRoute: AppCityRoute,
  AppCompaniesRoute: AppCompaniesRoute,
  AppCrmRoute: AppCrmRoute,
  AppDiscographyRoute: AppDiscographyRoute,
  AppFilesRoute: AppFilesRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppGratitudeRoute: AppGratitudeRoute,
  AppKanbanRoute: AppKanbanRoute,
  AppNotesRoute: AppNotesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStickyNotesRoute: AppStickyNotesRoute,
  AppStockRoute: AppStockRoute,
  AppTrendsRoute: AppTrendsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
